language: node_js
sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t kevinh94/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kevinh94/docker-react npm run test -- --coverage
